on: [push]

name: build-and-test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-rust

      - name: Run cargo test
        shell: bash
        run: cargo test --workspace
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-rust

      - name: Run cargo build
        shell: bash
        run: cargo build --workspace

      - name: Run cargo clippy
        shell: bash
        run: cargo clippy --workspace

      - name: Run format check
        shell: bash
        run: cargo fmt --check
